### ISSUE TITLE
Testing Party: Cannot set the trip time to the next day

### ISSUE THREAD

**Issue by Chinnu1103** [gcivil-nyu-org/Wednesday-Fall2023-Team-5#166]
User: test 6
Description: I was trying to create a trip for tomorrow but it gives an error saying that the trip start date should be in the future. Probably a timezone bug? Pasting the below image for reference:

![image](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-5/assets/32939338/4a6883b0-3243-4c9f-9e73-2c82dde97805)

**Comment by mike-zaharchenko17** [comment]
@Chinnu1103 Good catch, thank you. Fixed in our most recent integration PR- will be pushing to prod after the testing party.
