### ISSUE TITLE
Testing Party: Age range is getting accepted in negatives and zeros

### ISSUE THREAD

**Issue by Shre26ya** [gcivil-nyu-org/Wednesday-Fall2023-Team-5#170]
The age range is getting accepted in negatives and zeros. There is no validation.

<img width="1422" alt="Screenshot 2023-11-17 at 7 23 15 PM" src="https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-5/assets/40134985/a2030295-012d-4b1d-b6f6-1252230cd74b">

**Comment by mike-zaharchenko17** [comment]
Good catch. Was fixed earlier today in the most recent PR to integration. Will be merged to prod after testing party.
