### ISSUE TITLE
Testing party feedback: Timezone mismatch for validation

### ISSUE THREAD

**Issue by himanshu1196** [gcivil-nyu-org/Wednesday-Fall2023-Team-5#171]
What I did : Used "Plan trip" page to create a trip starting tomorrow
What went wrong : Trip was not created and an error was displayed "Start date must be in the future" even though the date is in the future.
It might be a django timezone mismatch related issue - in which case you can specify the timezone in settings.py
![Screenshot (110)](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-5/assets/14277620/08628927-cb85-46ed-91f5-aa23e0eecde7)

**Comment by mike-zaharchenko17** [comment]
Fixed earlier today in a PR to integration- will be pushed to prod after testing party
