### ISSUE TITLE
As a user, I want to be able to edit and delete my account profile.

### ISSUE THREAD

**Issue by rishienandhan3** [gcivil-nyu-org/Wednesday-Fall2023-Team-5#18]
**Tasks**
*Backend Tasks*
1. Implement edit profile functionality
2. Implement delete profile functionality

*Frontend Tasks*
1. Add edit profile functionality in profile page
2. Add delete profile functionality in profile page

**Acceptance criteria**
1. The user is able to edit/modify their profile 
2. The modified profile is reflected back on the screen

**Definition of Done**
Successful deployment post unit testing and code review and seamless integration with existing components

**Comment by sawyer1997** [comment]
As, this was a dependent feature on how the user models would be developed. And post completion of the other user story, didn't leave much time in which we can successfully complete the story. And hence this was not completed for most part of it.

VERDICT: Not DONE

This would also go into the backlog for the next sprint.
