### ISSUE TITLE
As a user, I want to be able to reset my account via email if I forget my password or username.

### ISSUE THREAD

**Issue by kravisankaran** [gcivil-nyu-org/Wednesday-Fall2023-Team-5#5]
**Acceptance criteria**
1. The user is able to provide the email address for password reset
2. The email with link to the password reset page is sent to user’s inbox 
3. The user is able to reset the password by following the link

**Definition of Done**
Successful deployment post unit testing and code review and seamless integration with existing components

**Comment by sawyer1997** [comment]
#112
