### ISSUE TITLE
As a user, I want to be able to create my account profile.

### ISSUE THREAD

**Issue by kravisankaran** [gcivil-nyu-org/Wednesday-Fall2023-Team-5#7]
**Tasks**
*Backend Tasks*
1. Finalize list of fields required for a user profile
2. Create data models in code 
3. Add image data field to user model

*Frontend Tasks*
1. Create user profile page

**Acceptance criteria**
1. The user is able to create the profile
2. The profile gets stored in the DB
3. User details displayed back on the screen

**Definition of Done**
Successful deployment post unit testing and code review and seamless integration with existing components

**Comment by sawyer1997** [comment]
We were able to complete most of the tasks required to be called as DONE, except the image field to be added inside the user model. We figured out that sqllite was the root issue for the problem, and while postgres could've solved the problem, but it comes with own set of deployment related issues.

And hence, the adding image field should go be either merged with some other story or it would be a new story in itself.
