### ISSUE TITLE
As a user, I want to be able to set, edit and update my default filter preferences on my account profile.

### ISSUE THREAD

**Issue by kravisankaran** [gcivil-nyu-org/Wednesday-Fall2023-Team-5#9]
**Tasks**
*Backend Tasks*
1. Finalize list of filters for user matching
2. Categorize filters into soft and hard filters
3. Create filter preferences data model

*Frontend Tasks*
1. Allow users to select preferences in profile creation page

**Acceptance criteria**
1. The user is able to set/edit/update the filter preferences on their account profile

**Definition of Done**
Successful deployment post unit testing and code review and seamless integration with existing components

**Comment by sawyer1997** [comment]
We were able to figure out what would be the matching preferences, we would be going ahead with. And how their schemas are going to be inside DB. This tasks comes very closely under the update/edit profile, so this would go as backlog for the next sprint.
